language: node_js
node_js:
  - "7"
  - "8"
  - "9"
  - "10"
  - "stable"

# Use faster Docker architecture on Travis.
sudo: false
dist: trusty

script:        ./scripts/validate.sh
after_success: npm run coveralls
